# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Perch < Formula
  desc "Meshtastic command center — a fast dashboard for your LoRa mesh"
  homepage "https://github.com/StevenSSparks/perch"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/StevenSSparks/perch/releases/download/v0.1.0/perch_0.1.0_darwin_amd64.tar.gz"
      sha256 "2279a6e7eb9c5e321d1521c551dc48ad1295f83ab16810516678307c5d03cf3a"

      define_method(:install) do
        bin.install "perch"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/StevenSSparks/perch/releases/download/v0.1.0/perch_0.1.0_darwin_arm64.tar.gz"
      sha256 "f01d607040bfa436c69f096ed66ed9643f3203751c6a99507e9a182994b66cf4"

      define_method(:install) do
        bin.install "perch"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/StevenSSparks/perch/releases/download/v0.1.0/perch_0.1.0_linux_amd64.tar.gz"
      sha256 "a1fa5026fa3a21ea63bc0d35e436126c3bc32559be24abdf23333c7f827d8cf6"
      define_method(:install) do
        bin.install "perch"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/StevenSSparks/perch/releases/download/v0.1.0/perch_0.1.0_linux_arm64.tar.gz"
      sha256 "f624bbc7d7f067189aee6a0488dc4ecbb90b252731aa2f4dad75ea2d03ae5abc"
      define_method(:install) do
        bin.install "perch"
      end
    end
  end

  test do
    system "#{bin}/perch", "-version"
  end
end
